SRC = main.c ft_atoi.c ft_getchars.c ft_ini_matrix.c ft_isdigit.c ft_print_matrix.c ft_putstr.c ft_draw_square.c ft_print_max.c ft_is_map_valid.c ft_check_chars.c ft_is_printable.c

NAME = bsq

all: $(NAME)

$(NAME):
	cc -Werror -Wextra -Wall $(SRC) -o $(NAME)

clean:

fclean: clean
	rm $(NAME)

re: fclean all

